# Generated by Django 4.2 on 2023-05-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Назва')),
                ('serias', models.CharField(default='none', max_length=75, verbose_name='Серії')),
                ('poster', models.ImageField(default='none', max_length=75, upload_to='', verbose_name='Постер')),
                ('top1', models.CharField(default='none', max_length=150, verbose_name='Перший топ')),
                ('top2', models.CharField(default='none', max_length=150, verbose_name='Другий топ')),
                ('top3', models.CharField(default='none', max_length=150, verbose_name='Третій топ')),
                ('years_go', models.CharField(default='none', max_length=75, verbose_name='Вихід серілу')),
                ('country', models.CharField(default='USA', max_length=75, verbose_name='Країни')),
                ('djanrs', models.CharField(max_length=50, verbose_name='Жанри')),
                ('about', models.TextField(verbose_name='Про:')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Серіал',
                'verbose_name_plural': 'Серіали',
            },
        ),
        migrations.CreateModel(
            name='serias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_series', models.CharField(max_length=75, verbose_name='Серія')),
                ('video_series', models.FileField(upload_to='./serials')),
                ('Base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Base_Serials', to='serials_page.base')),
            ],
        ),
    ]
